### ISSUE TITLE
Zoom and Pan

### ISSUE THREAD

**Issue by Davejkane** [Davejkane/riv#22]
* Add ZoomIn, ZoomOut, PanUp, PanDown, PanRight & PanLeft to `Action` enum in `ui.rs`
* Otherwise make a new ZoomAction enum with two variants, and a PanAction enum with the four variants and add `Zoom(ZoomAction)` to the `Action` enum and `Pan(PanAction)` to the `Action` enum
* Match `i` and `UpArrow` to ZoomIn
* Match `o` and `DownArrow` to ZoomOut
* Match `shift+arrow keys` and `shift+j,k,l,;` to Pan directions.

In the zoom function limit zoom in to 10x size and limit zoom out to actual size for images smaller than screen, or fit screen for images larger than screen. 

In the pan function limit panning to not allow image edge to go past screen edge. It shouldn't be possible to pan the image more than that.

**Comment by ori155** [comment]
Hi,
I'd like to take this one.
I think I'll take the ZoomAction and PanAction approach, as I think it will be easier to extend later if needed.

**Comment by Davejkane** [comment]
Excellent. It's all yours. Thanks a lot for getting involved.

**Comment by gurgalex** [comment]
Hi @ori155 

There has been a large refactor in the past few days #34 (issue #28)
 
The development of #37 will be relevant as well shortly.

**Comment by Davejkane** [comment]
Hi @ori155. I don't want to put any pressure on, but can you please clarify if you're still taking care of this? If not I'd like to have a look at it.

**Comment by gurgalex** [comment]
@Davejkane I'd like to work on this while waiting for the implementation of #40 to finalize (which NickHackman is working on in #58)

**Comment by gurgalex** [comment]
@Davejkane  a couple questions.

if someone pans 100 pixels right and 100 pixels down from center, then toggles back and forth between actual fit and fit to screen. Should the `offset` from center be preserved? What about the zoom level?

I'd go with both being preserved between toggling.

I assume the `offset` should be reset to centered on image change.

Should the zoom level be reset when moving between images?

**Comment by Davejkane** [comment]
@gurgalex. In my mind neither the offset or the zoom should be preserved if you start playing with the z key. Totally fine for that to just centre the image, unless it's easier to implement it with preserving, in which case go ahead.

And yes, I'd expect zoom and pan to be reset when changing images.

**Comment by gurgalex** [comment]
What should each of the `j` `k` `l` and `;` keys correspond to in pan directions?

**Comment by Davejkane** [comment]
J = down, K = up, H = left, L = right. Sorry I said semi-colon. Was getting mixed up between vim and i3. Just the same as vim.

**Comment by Davejkane** [comment]
@gurgalex. Now that Nick's branch is released, do you want to focus on Numerical arguments and I'll take this one? Or do you still want to do this one as well?

**Comment by gurgalex** [comment]
@Davejkane 
I'll take Numerical arguments. 

Hard part in this is zooming in.

**Comment by ori155** [comment]
Hi, It seems I can't put the time right now in order to be in your pace, sorry about the late replay.
I'm leaving it to you @Davejkane .
