### ISSUE TITLE
Toggle actual size/fit to screen

### ISSUE THREAD

**Issue by Davejkane** [Davejkane/riv#23]
* Add `ToggleFit` to `Action` enum in `ui.rs`
* Add `actual_size` boolean to program
* Match `z` key to `ToggleFit` in `event_action` function in `ui.rs`
* Match `Action::ToggleFit` to `toggle_fit` function in `run` in `program.rs`
* in `toggle_fit` function flip the `actual_size` boolean
* When changing image in `Next, Prev, Move, First, Last` etc, reset the `actual_size` boolean. It should be true when both images are small than window, and false when any dimension is larger than the corresponding window dimension.
* Add new action to README.

**Comment by gurgalex** [comment]
So, pressing `z` should either zoom in or out on the image until it fits in the dimensions of the window?

**Comment by Davejkane** [comment]
Yes, pressing z should toggle between actual size and fit to window. The default for images smaller than the window should be actual size, and the default for images larger than the window should be fit to window.

**Comment by gurgalex** [comment]
Question. When the image is larger than the display and actual size is desired, should the viewport focus on the center of the image?

I'm heavily leaning toward centered.

#22 May be related 

Centered
```
xxxxx
xyyyx
xyyyx
xyyyx
xxxxx
```

Or

Top-left focus
```
yyyxx
yyyxx
yyyxx
xxxxx
xxxxx
```

**Comment by Davejkane** [comment]
I'd also definitely go with centred. Hadn't even thought of it as an option :)

**Comment by Davejkane** [comment]
Just a heads up, `canvas.copy_ex` let's you specify a centre point, which will make this much easier. 

https://rust-sdl2.github.io/rust-sdl2/sdl2/render/struct.Canvas.html#method.copy_ex

**Comment by gurgalex** [comment]
Nice! Just need to get the center point of the texture.

**Comment by gurgalex** [comment]
From what I've read, the center point for `copy_ex` is used to specify the point to rotate or flip along.
https://docs.rs/sdl2/0.32.2/sdl2/render/struct.Canvas.html#method.copy_ex
> Copies a portion of the texture to the current rendering target, **optionally rotating it by angle around the given center** and also flipping it top-bottom and/or left-right.

So, perhaps what needs to be done manually is:

1. Compute the texture center point
2. (tex_slice) Create a rectangle to select only an area as large as the destination dimensions (or an area only as large as the image dimensions) 
3.  Center the `tex_slice` center on the destination area center.
