### ISSUE TITLE
Prerequisites missing libsdl2-image-dev and libsdl2-ttf-dev

### ISSUE THREAD

**Issue by ramonsnir** [Davejkane/riv#24]
The readme file only specifies that SDL2 should be installed. The instructions linked only install libsdl2-dev, however libsdl2-image-dev and libsdl2-ttf-dev are also required.

Note: package names differ between distros, names taken from Ubuntu/Debian.

**Comment by Phate6660** [comment]
Here are the package names for Arch Linux that are required. 
(I saw this and thought I should list the packages needed for Arch.)

`sdl2`, `sdl2_image`, and `sdl2_ttf`.

**Comment by Davejkane** [comment]
Thanks guys. I've added some info to the README, including a request to make a PR for anyone who discovers specifics for their distro. Going to close this for now.
