### ISSUE TITLE
Command line flag for full screen

### ISSUE THREAD

**Issue by Davejkane** [Davejkane/riv#39]
Allow an extra command line flag in `cli.rs`, probably `-F` to allow the app to be launched in full screen mode. 

Currently the window is built before parsing the command line arguments, so this will need to be taken care of. After that it should just be a boolean, that defaults to false. If true the `let window = ` line in main will have to be built differently, with `resizable` removed, display bounds removed and position centred removed, and fullscreen added.

It could look like `let window = if fullscreen {...} else {...}`

**Comment by gurgalex** [comment]
@Davejkane can I take this issue (and refactoring cli), or are you already working on moving `cli` parsing to happen before window creation?

**Comment by Davejkane** [comment]
@gurgalex go for it. I hadn't started on it yet.

**Comment by gurgalex** [comment]
What shortcut key should switch between fullscreen and windowed mode?
`F` and `F11` seems like a good choice.

**Comment by Davejkane** [comment]
They seem like good choices to me.
