### ISSUE TITLE
Take Numeric arguments for Actions

### ISSUE THREAD

**Issue by Davejkane** [Davejkane/riv#48]
# Goal

Allow current operations to take numeric arguments, a la vim. For example, `5j` would move through 5 images. `10d` would delete the next 10 images (😱). `11G` would go to the 11th image, etc.

# Implementation

We're probably going to want to group all numeric keypresses to enter some kind of new State-Machine state. From there, further numeric keypresses will augment the number, and non-numeric keypresses will potentially dispatch an Action.

* Numeric keypresses will be both number keys AND numpad keys. They are probably separate key events in SDL.
* Alter the Action enum to contain numeric data (probably usize) for variants that would be valid for numeric operations
* Probably want a state machine enum, with `Normal` being the current app behaviour, and `Numeric` being the new state. 
* If in the `Numeric` state, we probably want separate keyhandling code. But output should be the same Action enum as the regular keyhandling code (now containing data). 
* Update all of the Program methods that can, to take a numeric argument. E.g. move, delete, copy. (Increment and decrement already do)
* When we enter the numeric state, we probably want to take over info bar and display the current number that builds as the user types. If an invalid argument follows from the numeric state, print a message on the infobar (this will mean refactoring the info bar to accept messages, which will also be useful later).

**Comment by gurgalex** [comment]
Hiya, I'd work to work on this if anybody else hasn't.

**Comment by gurgalex** [comment]
Questions.

`10d`
Would delete the next 10 images. The currently shown image would not be deleted.

If on image "2 of 5", images 1-2 would remain. While 3-5 are deleted.

Maybe an option or other key or key combo to be inclusive.

**Comment by Davejkane** [comment]
No, the current image would be deleted and 10 in total. At least that's how it works in vim

**Comment by gurgalex** [comment]
@Davejkane 
What should the errors be like if copying 5 out of 50 images succeeds?

Should the program continuing moving/deleting/copying files if it encounters at least one that already exists, or fails for another reason.

**Comment by Davejkane** [comment]
@gurgalex I would suggest to keep processing in the event of an error and the error message should indicate how many images failed to copy/move/delete. You may want to still `eprintln!` on each failure.
