### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by gurgalex** [Davejkane/riv#59]
# Problem

Does this app even run on Windows?

# Solution

## Windows versions to support
Any Windows version still serviced by Microsoft for Home users. This currently means Windows 10 only.

https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet

## How to Build SDL2 apps for Windows
Use [CI](https://github.com/japaric/trust) to output release builds?

## How to Develop on Windows
?

## Seeing if it works

I have a Windows 10 installation on my laptop. So n=1 testing for now.

**Comment by Davejkane** [comment]
I'm going to close this issue. We are tackling this separately in each issue where it is a problem.
