### ISSUE TITLE
What is the behavior of `-m` on image deletion?

### ISSUE THREAD

**Issue by gurgalex** [Davejkane/riv#65]
A couple questions I've come across while adding tests and refactoring `paths` for #48 

# Scenerio 1
`riv -m 50 "*.png"`

The directory has 1000 png files in it but only 50 are shown.

program shows `50 of 50`

## Questions
1. What should happen on image deletion/move?

Should the display show: `49 of 49`

or, load in the next image, and show `50 of 50` (current development behavior)

2. Should setting the `max` in command mode to the same `50` load in the next image that would have been shown? Display shows `50 of 50`. (Like a refresh)

3. What about adjusting the max to `100`. Should that show `100 of 100` after the command completes?

4. If the user sets the max to `10`  and is on image `20 of 50` should the display refresh and show `10 of 10` or keep the current `20 of 50`?

**Comment by Davejkane** [comment]
@gurgalex I think this is a reasonably niche issue and a bit of an edge case. It is worth thinking about, but I'm not going to turn this into a project issue just now. I don't have any strong opinions on the matter - as a user I don't think I'll be using the max feature often if at all - so I'm more than happy to let you decide what correctness should be in this case.

**Comment by gurgalex** [comment]
Alright, I'll settle on needing to refresh either the glob or change max
images to load more images. Makes for simpler code.
