### ISSUE TITLE
r -> RotateClockwise, R -> RotateAntiClockwise

### ISSUE THREAD

**Issue by Davejkane** [Davejkane/riv#77]
# Goal

It should be possible to rotate images in 90 degree increments, clockwise with `r`, anti-clockwise with `R`

# Implementation

* Add key handling for `r` and `R`
* Perhaps make a `Rotation` enum in the `ui::State` with the four variants.
* Decide whether or not it makes sense to persist the rotation on returning to a previously rotated image
  * On a new image rotation should be reset
  * On returning to a previously rotated image, either reset the rotation (easiest) OR
  * keep a vector of rotation enums (probably not worth it).

**Comment by gurgalex** [comment]
@Davejkane 

When rotating an image, did you want the zoom level to adjust if the rotated image will need a bigger zoom level to fit fully on the screen?

**Comment by gurgalex** [comment]
@Davejkane, are you still working on this?
