### ISSUE TITLE
Timeouts for success messages

### ISSUE THREAD

**Issue by gurgalex** [Davejkane/riv#83]
Edited: filename covered, not the current image

Success messages do not disappear until the UI is refreshed.

This means that  with the `ng` and `df` commands, the new or current image filename is only visible after performing another action.

A possible solution is having messages only last a short amount of time before bringing back the previous state of the infobar.

**Comment by Davejkane** [comment]
I just tried this out. When I define a new glob, the new image is displayed along with the success bar. Also on delete or move, the next image is shown. A timeout might be nice anyway, but I don't see any incorrect behaviour here.

**Comment by gurgalex** [comment]
Sorry, meant the filename is covered up by the success info message.
