### ISSUE TITLE
Flip image. Vertical and Horizontal

### ISSUE THREAD

**Issue by Davejkane** [Davejkane/riv#88]
# Goal

Be able to flip an image either horizontally or vertically.

# Implementation

* Add two new keys, `H` and `V` might be good choices.
* SDL2 will definitely have a way to flip and image
* Vertical and horizontal flips could probably be booleans in the ui state.

**Comment by gurgalex** [comment]
Hmm, we've already used `H` (Shift + h) for pan left.

Should the keys be lowercase `h` and `v`?

**Comment by Davejkane** [comment]
@gurgalex, yeah I guess that could work.

**Comment by gurgalex** [comment]
I'd like to work on this. Seems pretty straightforward.
